### ISSUE TITLE
git workflow needs more conditions

### ISSUE THREAD

**Issue by seemiller** [vmware-tanzu/community-edition#1516]
## Bug Report

The git workflow to automatically copy package documentation to the docs folder is triggering off pushes to any branch.

```yaml
on:
  push:
    paths:
      - addons/packages/**/*/[rR][eE][aA][dD][mM][eE].md
      - addons/repos/main.yaml
`

## Expected Behavior

The workflow should only run on pushes to main, and ignore tags.

```yaml
on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
    paths:
      - addons/packages/**/*/[rR][eE][aA][dD][mM][eE].md
      - addons/repos/main.yaml
```

## Environment Details

* Build version (`tanzu version`):  
* Operating System (client):
