### ISSUE TITLE
workflow branch condition accidentally deleted

### ISSUE THREAD

**Issue by seemiller** [vmware-tanzu/community-edition#1615]
## Bug Report

A [change](https://github.com/vmware-tanzu/community-edition/pull/1525/files#diff-978a775a8df270642549d125cd4d173f5e7ba588730ed6a681dc29f53352e827) accidentally delete the branch conditions for the workflow to copy package readme files to docs. 

Need to restore this code.
```yaml
    branches:
      - main
    tags-ignore:
      - "**"
```

## Expected Behavior

The workflow should only trigger on pushes to `main`

## Environment Details

* Build version (`tanzu version`):  
* Operating System (client):
