### ISSUE TITLE
Proposal: Imagelinter to analyze `kbld` and `ytt` bundle output

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#1723]
## Problem statement

This is a follow up issue from https://github.com/vmware-tanzu/community-edition/pull/1302

Currently, the `hack/imagelinter` program checks for images in arbitrary `image:` yaml keys. This will generate a significant number of false positives and require the maintainers to keep an updated list of images to ignore. For example, consider the following basic yaml bundle and kbld configuration:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
overrides:
- image: nginx:1.14.2
  newImage: ubuntu  #! Replaces nginx with ubuntu in the kbld bundle
```

Notice in the `kbld` config, we explicitly override the nginx image and replace it with ubuntu. Then, when this yaml is rendered using the following command:
```
❯ kbld -f test.yaml
resolve | final: nginx:1.14.2 -> index.docker.io/library/ubuntu@sha256:9d6a8699fb5c9c39cf08a0871bd6219f0400981c570894cd8cbea30d3424a31f
...
```
we get this output
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kbld.k14s.io/images: |
      - Metas:
        - Tag: latest
          Type: resolved
          URL: ubuntu
        URL: index.docker.io/library/ubuntu@sha256:9d6a8699fb5c9c39cf08a0871bd6219f0400981c570894cd8cbea30d3424a31f
  labels:
    app: nginx
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: index.docker.io/library/ubuntu@sha256:9d6a8699fb5c9c39cf08a0871bd6219f0400981c570894cd8cbea30d3424a31f
        name: nginx
        ports:
        - containerPort: 80
```
note that the _resolved_ bundle is _not_ referencing nginx images anywhere. The image lock file looks like this and points the `nginx` image at the `ubuntu` sha:
```yaml
---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: nginx:1.14.2
  image: index.docker.io/library/ubuntu@sha256:9d6a8699fb5c9c39cf08a0871bd6219f0400981c570894cd8cbea30d3424a31f
kind: ImagesLock
``` 

When running the image linter program against this example bundle, _both_ nginx and ubuntu are linted (since `image:` is the main referencing point for finding images to lint.

If for some arbitrary reason `nginx` images where not allowed to be shipped to customers, the imagelinter would generate a false positive here. The `kbld` bundle in this example that would get shipped to customers _would not_ include any `nginx` image at all.

## There has to be a better way!

Proposal: instead of searching for `image:` keys in the various static yaml bundles we ship, we should _generate_ the `kbld` bundle and look at the `ytt` output, using that as the source of truth for what images to lint.

#### Why not just look at the image lock file?

The image lock file is an ok indicator of what images we ship, but we should also be mindful of package authors who may have to use a dynamic overlay for their package images. Using overlays in this way results in _all images_ being referenced and resolved in the image lock file, including images that will ultimately be overlayed.

#### Why do we also need to look at the `ytt` output?

If we can't ultimately rely on the image lock file as a source of truth, and if package authors have the ability to use dynamic overlays for their images, in the end, we need to analyze the yaml bundle that gets shipped to customers. This includes the `ytt` output and any additional overlays that aren't accounted for by kbld.

#### Why not just look at the `latest` package repo and the already generated bundles in harbor?

Currently, we do not automatically update the package repos as part of updating the static yaml bundles in this GitHub repository. In other words, the only way we can analyze _changes_ and have a fast feedback loop is to generate the yaml from PRs or from within this code repository, not from bundles that live in harbor which may be out of date.
