### ISSUE TITLE
Pinniped not working for workload clusters non-admin users, only mgmt clusters

### ISSUE THREAD

**Issue by cormachogan** [vmware-tanzu/community-edition#1779]
## Bug Report

Following the procedure to get Identity Management with Pinniped/Dex to work with NSX-ALB (setting the services to be of type Load Balancer), it seems that we can only get "non-admin" users to work with the management cluster.

Trying to query the cluster using a "non-admin" context/user results in the following error:

```
% kubectl get nodes
Error: could not complete concierge credential exchange: could not login: tokencredentialrequests.login.concierge.pinniped.dev is forbidden: User "system:anonymous" cannot create resource "tokencredentialrequests" in API group "login.concierge.pinniped.dev" in the namespace "pinniped-concierge"
Error: pinniped-auth login failed: exit status 1
Error: exit status 1
Unable to connect to the server: getting credentials: exec: executable tanzu failed with exit code 1
```

## Expected Behavior

I would have expected to be able to work on both management and workload clusters as a non-admin user.

## Steps to Reproduce the Bug

Deploy management cluster
Follow procedure to change the overlays in pinniped to use Load Balancers.
Authenticate in Dex/create LDAP "non-admin" user on cluster
Confirm that I can query the cluster with this context

Deploy workload cluster
Create LDAP "non-admin" user on cluster
Try to query cluster as this - failure as highlighted above

## Environment Details

* Build version (`tanzu version`): 
TCE v0.8.0-rc2
version: v0.2.1
buildDate: 2021-09-13
sha: ceaa474

* Operating System (client):
macOS (big sur) v11.5.2
vSphere 7.0U2c
MS Server 2012 Active Directory/DC.

## Workload cluster details:

```
% tanzu cluster kubeconfig get workload --admin
Credentials of cluster 'workload' have been saved
You can now access the cluster by running 'kubectl config use-context workload-admin@workload'

% kubectl config use-context workload-admin@workload
Switched to context "workload-admin@workload".

% kubectl get apps -A
NAMESPACE    NAME                                DESCRIPTION           SINCE-DEPLOY   AGE
tkg-system   antrea                              Reconcile succeeded   2m             10m
tkg-system   load-balancer-and-ingress-service   Reconcile succeeded   3m30s          10m
tkg-system   metrics-server                      Reconcile succeeded   3m24s          10m
tkg-system   vsphere-cpi                         Reconcile succeeded   4m54s          10m
tkg-system   vsphere-csi                         Reconcile succeeded   2m2s           10m
chogan@chogan-a01 Manifests % kubectl get pods -A
NAMESPACE     NAME                                                     READY   STATUS    RESTARTS   AGE
avi-system    ako-0                                                    1/1     Running   0          10m
kube-system   antrea-agent-2th5q                                       2/2     Running   0          10m
kube-system   antrea-agent-l954s                                       2/2     Running   0          10m
kube-system   antrea-controller-c67f64c87-nhnln                        1/1     Running   0          10m
kube-system   coredns-8dcb5c56b-jnwb4                                  1/1     Running   0          16m
kube-system   coredns-8dcb5c56b-zsbzc                                  1/1     Running   0          16m
kube-system   etcd-workload-control-plane-hsbb5                        1/1     Running   0          16m
kube-system   kube-apiserver-workload-control-plane-hsbb5              1/1     Running   0          16m
kube-system   kube-controller-manager-workload-control-plane-hsbb5     1/1     Running   0          16m
kube-system   kube-proxy-bxvmp                                         1/1     Running   0          14m
kube-system   kube-proxy-wlzcp                                         1/1     Running   0          16m
kube-system   kube-scheduler-workload-control-plane-hsbb5              1/1     Running   0          16m
kube-system   metrics-server-595d9b7cd5-kgptb                          1/1     Running   0          10m
kube-system   vsphere-cloud-controller-manager-q5hf5                   1/1     Running   0          10m
kube-system   vsphere-csi-controller-57df99fb87-28tsz                  6/6     Running   0          9m47s
kube-system   vsphere-csi-node-b8b99                                   3/3     Running   0          9m47s
kube-system   vsphere-csi-node-zrv86                                   3/3     Running   0          9m47s
tkg-system    kapp-controller-585f669fcf-g4pzn                         1/1     Running   0          16m
tkg-system    tanzu-capabilities-controller-manager-69f58566d9-dxlgb   1/1     Running   0          16m
```

## Management cluster details:

```
% kubectl get apps -A
NAMESPACE    NAME                                DESCRIPTION           SINCE-DEPLOY   AGE
default      workload-kapp-controller            Reconcile succeeded   26s            41m
tkg-system   ako-operator                        Reconciling           19s            115m
tkg-system   antrea                              Reconcile succeeded   28s            115m
tkg-system   load-balancer-and-ingress-service   Reconcile succeeded   5m17s          107m
tkg-system   metrics-server                      Reconcile succeeded   105s           115m
tkg-system   pinniped                            Reconcile succeeded   85s            115m
tkg-system   tanzu-addons-manager                Reconcile succeeded   88s            120m
tkg-system   vsphere-cpi                         Reconcile succeeded   5m19s          115m
tkg-system   vsphere-csi                         Reconcile succeeded   61s            115m

% kubectl get all -n pinniped-supervisor
NAME                                       READY   STATUS      RESTARTS   AGE
pod/pinniped-post-deploy-job-frlnd         0/1     Completed   0          57m
pod/pinniped-supervisor-594c885c75-2kj94   1/1     Running     0          57m
pod/pinniped-supervisor-594c885c75-77dw6   1/1     Running     0          57m

NAME                          TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)         AGE
service/pinniped-supervisor   LoadBalancer   100.65.160.145   10.27.62.18   443:30097/TCP   117m

NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/pinniped-supervisor   2/2     2            2           117m

NAME                                             DESIRED   CURRENT   READY   AGE
replicaset.apps/pinniped-supervisor-594c885c75   2         2         2       117m

NAME                                 COMPLETIONS   DURATION   AGE
job.batch/pinniped-post-deploy-job   1/1           11s        57m

% kubectl get all -n pinniped-concierge
NAME                                              READY   STATUS    RESTARTS   AGE
pod/pinniped-concierge-7f784cf884-62ckx           1/1     Running   0          117m
pod/pinniped-concierge-7f784cf884-z5w8p           1/1     Running   0          117m
pod/pinniped-concierge-kube-cert-agent-473b559b   1/1     Running   0          113m
pod/pinniped-concierge-kube-cert-agent-618f9671   1/1     Running   0          113m
pod/pinniped-concierge-kube-cert-agent-c2ca0de1   1/1     Running   0          113m

NAME                             TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/pinniped-concierge-api   ClusterIP   100.65.143.106   <none>        443/TCP   117m

NAME                                 READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/pinniped-concierge   2/2     2            2           117m

NAME                                            DESIRED   CURRENT   READY   AGE
replicaset.apps/pinniped-concierge-7f784cf884   2         2         2       117m
```

Looking at the pinniped add-on secret on the management cluster:

```
% kubectl get secret mgmt-pinniped-addon -n tkg-system -o jsonpath='{.data}'
{"overlays.yaml":"I0A[...]wcwo=","values.yaml":"I0BkY[...]b20K"}%

--

% echo 'I0Agb[...]wcwo=' | base64 -D
#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind": "Service", "metadata": {"name": "pinniped-supervisor", "namespace": "pinniped-supervisor"}})
---
#@overlay/replace
spec:
  type: LoadBalancer
  selector:
    app: pinniped-supervisor
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443


#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind": "Service", "metadata": {"name": "dexsvc", "namespace": "tanzu-system-auth"}}), missing_ok=True
---
#@overlay/replace
spec:
  type: LoadBalancer
  selector:
    app: dex
  ports:
    - name: dex
      protocol: TCP
      port: 443
      targetPort: https

--

% echo 'I0Bk[...]b20K' | base64 -D

#@data/values
#@overlay/match-child-defaults missing_ok=True
---
infrastructure_provider: vsphere
tkg_cluster_role: management
custom_cluster_issuer: ""
custom_tls_secret: ""
http_proxy: ""
https_proxy: ""
no_proxy: ""
identity_management_type: ldap
pinniped:
  cert_duration: 2160h
  cert_renew_before: 360h
  supervisor_svc_endpoint: https://0.0.0.0:31234
  supervisor_ca_bundle_data: ca_bundle_data_of_supervisor_svc
  supervisor_svc_external_ip: 0.0.0.0
  supervisor_svc_external_dns: null
  upstream_oidc_client_id: ""
  upstream_oidc_client_secret: ""
  upstream_oidc_issuer_url: https://0.0.0.0:30167
  upstream_oidc_tls_ca_data: ca_bundle_data_of_dex_svc
  upstream_oidc_additional_scopes:
  - email
  - profile
  - groups
  upstream_oidc_claims:
    username: name
    groups: groups
dex:
  app: dex
  create_namespace: true
  namespace: tanzu-system-auth
  organization: vmware
  commonname: tkg-dex
  config:
    connector: ldap
    frontend:
      theme: tkg
    web:
      https: 0.0.0.0:5556
      tlsCert: /etc/dex/tls/tls.crt
      tlsKey: /etc/dex/tls/tls.key
    expiry:
      signingKeys: 90m
      idTokens: 5m
      authRequests: 90m
      deviceRequests: 5m
    logger:
      level: info
      format: json
    staticClients:
    - id: pinniped
      redirectURIs:
      - https://0.0.0.0/callback
      name: pinniped
      secret: dummyvalue
    ldap:
      host: dc01.rainpole.com:636
      insecureNoSSL: false
      startTLS: null
      rootCA: null
      rootCAData: LS0tL[...]0tLQ==
      bindDN: cn=Administrator,cn=Users,dc=rainpole,dc=com
      BIND_PW_ENV_VAR: *********
      usernamePrompt: LDAP Username
      insecureSkipVerify: false
      userSearch:
        baseDN: cn=Users,dc=rainpole,dc=com
        filter: (objectClass=person)
        username: userPrincipalName
        idAttr: DN
        emailAttr: DN
        nameAttr: userPrincipalName
        scope: sub
      groupSearch:
        baseDN: dc=rainpole,dc=com
        filter: (objectClass=group)
        nameAttr: ""
        scope: sub
        userMatchers:
        - userAttr: ""
          groupAttr: ""
    oauth2:
      skipApprovalScreen: true
      responseTypes:
      - code
    storage:
      type: kubernetes
      config:
        inCluster: true
    enablePasswordDB: false
  service:
    name: dexsvc
    type: null
  deployment:
    replicas: 1
  certificate:
    duration: 2160h
    renewBefore: 360h
  dns:
    vsphere:
      dnsNames:
      - tkg-dex.com
      ipAddresses:
      - 0.0.0.0
    aws:
      dnsNames:
      - tkg-dex.com
      DEX_SVC_LB_HOSTNAME: example.com
    azure:
      dnsNames:
      - tkg-dex.com
      DEX_SVC_LB_HOSTNAME: dex.example.com
```
