### ISSUE TITLE
[package plugin] Create a values file from the schema

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#1946]
## Feature request
I would love to have a values file (yaml) created as output of the schema request for a package. e.g.

```
tanzu package available get contour.community.tanzu.vmware.com/1.17.1 --values-schema-file my-file.yaml
```

That should give me a yaml file, and the schema should come as comments

```
#! The namespace in which to deploy Contour and Envoy. 
namespace: projectcontour

contour:
  #! How many Contour pod replicas to have.
  replicas: 2

  #! Whether to enable PROXY protocol for all Envoy listeners.
  useProxyProtocol: false

  #! The Contour log level. Valid options are "info" and "debug".
  logLevel: info

#! Settings for the Envoy component.
envoy:
  #! Envoy service settings.
  service:
    #! The type of Kubernetes service to provision for Envoy.
    type: LoadBalancer

    #! The external traffic policy for the Envoy service. If type is "ClusterIP", this field is ignored.
    externalTrafficPolicy: Local

    #! Annotations to set on the Envoy service.
    annotations: {}

    #! NodePort settings for the Envoy service. If type is not "NodePort",
    #! these settings are ignored.
    nodePorts:
      #! If type == NodePort, the node port number to expose Envoy's HTTP listener on.
      #! If not specified, a node port will be auto-assigned by Kubernetes.
      http: null
      #! If type == NodePort, the node port number to expose Envoy's HTTPS listener on.
      #! If not specified, a node port will be auto-assigned by Kubernetes.
      https: null

  #! Host port settings for the Envoy pods.
  hostPorts:
    #! Whether to enable host ports. If false, http & https are ignored.
    enable: false
    #! If enable == true, the host port number to expose Envoy's HTTP listener on.
    http: 80
    #! If enable == true, the host port number to expose Envoy's HTTPS listener on.
    https: 443

  #! Whether to enable host networking for the Envoy pods.
  hostNetwork: false

  #! The termination grace period, in seconds, for the Envoy pods.
  terminationGracePeriodSeconds: 300

  #! The Envoy log level.
  logLevel: info

#! Settings for the TLS certificates for securing communication between Contour and Envoy.
certificates:
  #! Whether to use cert-manager to provision TLS certificates for securing
  #! communication between Contour and Envoy. If false, the upstream Contour
  #! certgen job will be used to provision certificates. If true, the
  #! cert-manager addon must be installed in the cluster.
  useCertManager: false

  #! If using cert-manager, how long the certificates should be valid for.
  #! If useCertManager is false, this field is ignored.
  duration: 8760h

  #! If using cert-manager, how long before expiration the certificates should
  #! be renewed. If useCertManager is false, this field is ignored.
  renewBefore: 360h
```

That will be much handier than the current --values-schema which is more a descriptive help.

```
tanzu package available get contour.community.tanzu.vmware.com/1.17.1 --values-schema
| Retrieving package details for contour.community.tanzu.vmware.com/1.17.1... 
  KEY                                  DEFAULT         TYPE     DESCRIPTION                                                                                                                                                                                                                                                           
  certificates.duration                8760h           string   If using cert-manager, how long the certificates should be valid for. If useCertManager is false, this field is ignored.                                                                                                                                              
  certificates.renewBefore             360h            string   If using cert-manager, how long before expiration the certificates should be renewed. If useCertManager is false, this field is ignored.                                                                                                                              
  certificates.useCertManager          false           boolean  Whether to use cert-manager to provision TLS certificates for securing communication between Contour and Envoy. If false, the upstream Contour certgen job will be used to provision certificates. If true, the cert-manager addon must be installed in the cluster.  
  contour.configFileContents           <nil>           object   The YAML contents of the Contour config file. See https://projectcontour.io/docs/v1.17.1/configuration/#configuration-file for more information.                                                                                                                      
  contour.logLevel                     info            string   The Contour log level. Valid options are info and debug.                                                                                                                                                                                                              
  contour.replicas                     2               integer  How many Contour pod replicas to have.                                                                                                                                                                                                                                
  contour.useProxyProtocol             false           boolean  Whether to enable PROXY protocol for all Envoy listeners.                                                                                                                                                                                                             
  envoy.hostPorts.https                443             integer  If enable == true, the host port number to expose Envoy's HTTPS listener on.                                                                                                                                                                                          
  envoy.hostPorts.enable               false           boolean  Whether to enable host ports. If false, http and https are ignored.                                                                                                                                                                                                   
  envoy.hostPorts.http                 80              integer  If enable == true, the host port number to expose Envoy's HTTP listener on.                                                                                                                                                                                           
  envoy.logLevel                       info            string   The Envoy log level.                                                                                                                                                                                                                                                  
  envoy.service.annotations            <nil>           object   Annotations to set on the Envoy service.                                                                                                                                                                                                                              
  envoy.service.externalTrafficPolicy  Local           string   The external traffic policy for the Envoy service.                                                                                                                                                                                                                    
  envoy.service.nodePorts.http         <nil>           integer  If type == NodePort, the node port number to expose Envoy's HTTP listener on. If not specified, a node port will be auto-assigned by Kubernetes.                                                                                                                      
  envoy.service.nodePorts.https        <nil>           integer  If type == NodePort, the node port number to expose Envoy's HTTPS listener on. If not specified, a node port will be auto-assigned by Kubernetes.                                                                                                                     
  envoy.service.type                   LoadBalancer    string   The type of Kubernetes service to provision for Envoy.                                                                                                                                                                                                                
  envoy.terminationGracePeriodSeconds  300             integer  The termination grace period, in seconds, for the Envoy pods.                                                                                                                                                                                                         
  envoy.hostNetwork                    false           boolean  Whether to enable host networking for the Envoy pods.                                                                                                                                                                                                                 
  namespace                            projectcontour  string   The namespace in which to deploy Contour and Envoy.
```

The output should be optimized so that it follows a ytt-schema. Maybe a message at the top saying those are the default values, change the ones you want to change, remove those you don't want to change.

tanzu-framework issue: https://github.com/vmware-tanzu/tanzu-framework/issues/674
