### ISSUE TITLE
V1 Ingress now works with TLS validation

### ISSUE THREAD

**Issue by mikegehard** [vmware-tanzu/community-edition#2174]
## Description

Down towards the bottom there is a paragraph that reads:
```
NOTE: If you’re using Ingress, TLS Delegation no longer works with the latest of the networking.k8s.io apiGroup (v1). You need to use previous version of the API (v1beta1), or use the more advanced HTTPProxy.
```

I'm not sure this is true any longer.

With the following packages installed:
```
➜  community-edition-setup tanzu package installed list
\ Retrieving installed packages...
  NAME          PACKAGE-NAME                             PACKAGE-VERSION  STATUS
  cert-manager  cert-manager.community.tanzu.vmware.com  1.5.3            Reconcile succeeded
  contour       contour.community.tanzu.vmware.com       1.18.1           Reconcile succeeded
```

I can use the Ingress definition:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: sample.tce.rubbersidedowntech.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sample
            port:
              number: 8080
  tls:
  - secretName: sample
    hosts:
    - sample.tce.rubbersidedowntech.dev
```

And get a perfectly good SSL Ingress object with I `kubectl apply`.
## Location

https://tanzucommunityedition.io/docs/latest/solutions-secure-ingress/
