### ISSUE TITLE
Update Credentials Specification in Velero Readme 

### ISSUE THREAD

**Issue by seemiller** [vmware-tanzu/community-edition#2373]
## Bug Report

Community reported problems running the Velero package, specifically `Access Denied` errors after installing the package and attempting to perform a backup on AWS.

After a bit of debugging, it seems that the fix is to add `[default]` before specifying your AWS credentials.

The documentation currently says to declare your credentials in a values.yaml file in this format:

```yaml
      secretContents:
        cloud: |
          aws_access_key_id=${AWS_ACCESS_KEY}
          aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}
```

The fix that worked for both myself and the community member was to do this. This is how the official Velero documentation says to provide these values.

```yaml
      secretContents:
        cloud: |
          [default]
          aws_access_key_id=${AWS_ACCESS_KEY}
          aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}
```

## Expected Behavior

Backups should work without access problems.

## Steps to Reproduce the Bug

- Follow the existing AWS install directions.
- Make a backup
- Get an Access Denied error

## Environment Details

* Build version (`tanzu version`): 
* Deployment (Managed/Standalone cluster): 
* Infrastructure Provider (Docker/AWS/Azure/vSphere): 
* Operating System (client):
