### ISSUE TITLE
vsphere-csi 2.3.0 package adds annotation as an integer

### ISSUE THREAD

**Issue by vijaykatam** [vmware-tanzu/community-edition#2406]
## Bug Report

vsphere-csi 2.3.0 package adds label to the daemonset that can be sometimes an integer if the sha256 result of data values yields a string with all numeric characters in the first seven tokens. This can cause k8s to interpret the label to be integer causing overflow error and the daemonset install fails

## Expected Behavior

Trimmed data value hash should be a string

## Steps to Reproduce the Bug

Use sample data values like 
```
#@data/values
#@overlay/match-child-defaults missing_ok=True

---
vsphereCSI:
  namespace: kube-system
  clusterName: cluster-test
  server: 10.1.1.1
  datacenter: ds-test
  publicNetwork: test
  username: test
  password: test
  provisionTimeout: 300s
  attachTimeout: 3000s
  vSphereVersion: 6.7.0
```

## Environment Details

* Build version (`tanzu version`): 1.4
* Deployment (Managed/Standalone cluster): Managed
* Infrastructure Provider (Docker/AWS/Azure/vSphere):  vSphere
* Operating System (client): macOS
