### ISSUE TITLE
Expose /v2/ timeout parameter as config option for Harbor's HTTPProxy

### ISSUE THREAD

**Issue by doddatpivotal** [vmware-tanzu/community-edition#2435]
## Feature Request

I have found that when harbor has very large images.  Tanzu Build Service for instance has some 6GB+ OCI images for its builders, end of file errors occur when attempting to retrieve the images.  I have applied the following overlay to increase the timeout from 60s to 5m and the pull was successful.  It took 3m28s.   A user should not have to create this overlay.  It would be best if the timeout value was configurable via the packages data-values.yaml file.

```
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "HTTPProxy","metadata":{"name":"harbor-httpproxy"}})
---
spec:
  routes:
  #@overlay/match by=lambda indexOrKey, left, right: left["conditions"][0]["prefix"].endswith("/v2/")
  - conditions:
    #@overlay/match missing_ok=True
    timeoutPolicy:
      response: 300s
```
