### ISSUE TITLE
Guidelines on running without kube-proxy

### ISSUE THREAD

**Issue by jayunit100** [vmware-tanzu/community-edition#2608]
## Description

Users might want to test different service proxies out:
- AntreaProxy with the `all` mode (needs to kube proxy)
- Testing of KPNG https://github.com/kubernetes-sigs/kpng/tree/master/backends 

It would be nice if we had a guideline on how to disable kube-proxy.

In general tools like kind/minkube support this (https://github.com/kubernetes/minikube/issues/12389, https://kind.sigs.k8s.io/docs/user/configuration/#:~:text=To%20disable%20kube%2Dproxy%2C%20set,the%20mode%20to%20%22none%22%20. )

## Additional Context

Interestingly, looking at cluster api:

https://github.dev/kubernetes-sigs/cluster-api/blob/main/controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go

the kubeadm_control_plane_webhook.go doesnt have a top level knob for kube proxy, likely because its an addon

```
const (
	spec                 = "spec"
	kubeadmConfigSpec    = "kubeadmConfigSpec"
	clusterConfiguration = "clusterConfiguration"
	initConfiguration    = "initConfiguration"
	joinConfiguration    = "joinConfiguration"
	nodeRegistration     = "nodeRegistration"
	preKubeadmCommands   = "preKubeadmCommands"
	postKubeadmCommands  = "postKubeadmCommands"
	files                = "files"
	users                = "users"
	apiServer            = "apiServer"
	controllerManager    = "controllerManager"
	scheduler            = "scheduler"
	ntp                  = "ntp"
)
```

Correspondingly, in tanzu framework, our CAPI YTT also doesnt have a hook to modify kube proxy, abbreviating the kubeadmControlPlane, we can see:

```
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: '${ CLUSTER_NAME }-control-plane'
  namespace: '${ NAMESPACE }'
spec:
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: VSphereMachineTemplate
      name: '${ CLUSTER_NAME }-control-plane'
  kubeadmConfigSpec:
    useExperimentalRetryJoin: true
    clusterConfiguration:
      imageRepository: '${ _TKG_K8S_IMAGE_REPOSITORY }'     
      etcd: ...
      dns: ...
      apiServer: ...
      scheduler: ...
    ...
    files:
    - content: |
        apiVersion: v1
        kind: Pod
        metadata:
        spec:
          containers:
          - args:
            - start
            env:
            - name: vip_arp
          volumeMounts:
            - mountPath: /etc/kubernetes/admin.conf
              name: kubeconfig
          hostNetwork: true
          volumes:
            name: kubeconfig
        status: {}
      owner: root:root
      path: /etc/kubernetes/manifests/kube-vip.yaml
    initConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cloud-provider: external
          tls-cipher-suites:         name: '{{ ds.meta_data.hostname }}'
    joinConfiguration:
      nodeRegistration:
        criSocket: /var/run/containerd/containerd.sock
        kubeletExtraArgs:
          cloud-provider: external
    preKubeadmCommands:
    users:
---
```

Im assuming theres an api hook somehow in the YAML for disabling kube proxy but not sure what it is, kubeadm `skip-phases` = `kube-proxy` 

@rajaskakodkar
