### ISSUE TITLE
Upgrade kapp-controller to `0.30`

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#2785]
This request was sourced in some capability work individuals want to bring into TCE.

**Comment by joshrosso** [comment]
Current state of TCE kapp-controller is that we are bound to the versions shipped by our commercial product Tanzu Kubernetes Grid (TKG). We'll target this for the v0.11.0 release, currently aiming for the March timeframe.

**Comment by seemiller** [comment]
Current version of kapp-controller is `0.32.0`, are we still locked to `0.30.0` in framework?

**Comment by joshrosso** [comment]
I will investigate this today.

Due to https://github.com/vmware-tanzu/community-edition/issues/3275#event-6156944162, we need to keep our BOM at the same version as v1.5.1. That will determine our kapp-controller version.

If it's below v0.30, this issue will be moved out to another milestone.

**Comment by joshrosso** [comment]
This should be part of our next release. Our plan is is to pin to the TKG v1.5.1 BOM. Here is the evidence of the kapp-controller version:


`tkr-compatibility`:

```yaml
version: v11
managementClusterVersions:
- version: v1.5.1
  supportedKubernetesVersions:
  - v1.22.5+vmware.1-tkg.3
  - v1.21.8+vmware.1-tkg.4
  - v1.20.14+vmware.1-tkg.4
- version: v1.5.0
  supportedKubernetesVersions:
  - v1.22.5+vmware.1-tkg.1
  - v1.21.8+vmware.1-tkg.1
  - v1.20.14+vmware.1-tkg.1
- version: v1.4.2
  supportedKubernetesVersions:
  - v1.21.8+vmware.1-tkg.2
  - v1.19.16+vmware.1-tkg.1
  - v1.20.14+vmware.1-tkg.2
- version: v1.4.1
  supportedKubernetesVersions:
  - v1.21.2+vmware.1-tkg.2
  - v1.20.8+vmware.1-tkg.3
  - v1.19.12+vmware.1-tkg.2
- version: v1.3.0
  supportedKubernetesVersions:
  - v1.20.4+vmware.1-tkg.1
  - v1.19.8+vmware.1-tkg.1
  - v1.18.16+vmware.1-tkg.1
  - v1.17.16+vmware.2-tkg.1
- version: v1.3.1
  supportedKubernetesVersions:
  - v1.19.8+vmware.3-tkg.1
  - v1.20.5+vmware.2-tkg.1
  - v1.18.17+vmware.2-tkg.1
  - v1.20.4+vmware.3-tkg.1
  - v1.19.9+vmware.2-tkg.1
  - v1.18.16+vmware.3-tkg.1
  - v1.17.16+vmware.3-tkg.1
- version: v1.3.1-fips.1
  supportedKubernetesVersions:
  - v1.20.5+vmware.2-fips.1-tkg.1
- version: v1.3.1-patch1
  supportedKubernetesVersions:
  - v1.19.8+vmware.3-tkg.1
  - v1.20.5+vmware.2-tkg.1
  - v1.18.17+vmware.2-tkg.1
  - v1.20.4+vmware.3-tkg.1
  - v1.19.9+vmware.2-tkg.1
  - v1.18.16+vmware.3-tkg.1
  - v1.17.16+vmware.3-tkg.1
- version: v1.4.0
  supportedKubernetesVersions:
  - v1.19.12+vmware.1-tkg.1
  - v1.21.2+vmware.1-tkg.1
  - v1.20.8+vmware.1-tkg.2
- version: v1.4.0-fips.1
  supportedKubernetesVersions:
  - v1.21.2+vmware.1-fips.1-tkg.1
  - v1.20.8+vmware.1-fips.1-tkg.2
```

`projects.registry.vmware.com/tkg/tkr-bom:v1.22.5_vmware.1-tkg.3`:

```sh
$ rg -i 'kapp-controller' -A 3

tkr-bom-v1.22.5+vmware.1-tkg.3.yaml
92:  kapp-controller:
93-  - version: v0.30.0+vmware.1
94-    images:
95-      kappControllerImage:
96:        imagePath: kapp-controller
97-        tag: v0.30.0_vmware.1
98-  kubernetes:
99-  - version: v1.22.5+vmware.1
--
188:      kapp-controller.tanzu.vmware.com:
189:        imagePath: packages/core/kapp-controller
190-        tag: v0.30.0_vmware.1-tkg.1
191-      load-balancer-and-ingress-service.tanzu.vmware.com:
192-        imagePath: packages/core/load-balancer-and-ingress-service
--
459:  kapp-controller:
460-    category: addons-management
461-    clusterTypes:
462-    - management
--
464:    packageName: kapp-controller.tanzu.vmware.com
465-  load-balancer-and-ingress-service:
466-    category: networking
467-    clusterTypes:
```
