### ISSUE TITLE
[Knative package] Support additional values for knative package

### ISSUE THREAD

**Issue by vrabbi** [vmware-tanzu/community-edition#3129]
## Feature Request
Add additional configurations to kantive serving package.
currently the package is very minimalistic in its config options. the main flag that would helpful to add is to update the config-network configmap in the knative-serving namespace to allow setting a different naming template (domain-template field) for service FQDNs.
The default value is "{{.Name}}.{{.Namespace}}.{{.Domain}}". this value is not great if we want to do TLS certs and is much easier to use something like "{{.Name}}-{{.Namespace}}.{{.Domain}}".

## Describe alternatives you've considered
Currently i have an overlay i append to the package with the following content which could simply be added to the package itself as well and exposed via a data value:

```
#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"kind":"ConfigMap", "metadata": {"name": "config-network"}})
---
metadata:
  annotations:
    #@overlay/match missing_ok=True
    kapp.k14s.io/update-strategy: skip
data:
  #@overlay/match missing_ok=True
  #@yaml/text-templated-strings
  domain-template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
```

## Additional context
This would make day0 usage much easier especially for local setups. by adding the "kapp.k14s.io/update-strategy: skip" annotation we can make sure that we dont block users from changing this but it makes for in my opinion a much better default value then the current situation.
