### ISSUE TITLE
How should we approach `ProviderConfiguration` in unmanaged clusters

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#3344]
`ProviderConfiguration` is meant to accompany our generic cluster configuration with settings the apply only to the underlying provider. Today, the only provider is `kind`. With the PR https://github.com/vmware-tanzu/community-edition/pull/3304 we have moved to accepting a `string` for this value.

I really think, as we expand providers, it would benefit us to stick with the `ProviderConfiguration map[string]interface{}` representation and let providers offer a struct in their package/provider, where they offer a structured representation of their config options. For example, kind could simply become:

```yaml
providerConfiguration:
    rawKindConfig: |
        kind: Cluster
        apiVersion: kind.x-k8s.io/v1alpha4
        nodes:
        - role: control-plane
          extraPortMappings:
          - containerPort: 888
            hostPort: 888
            listenAddress: "127.0.0.1"
            protocol: TCP
        - role: worker
        - role: worker
```

If we introduced a `VM` provider in the future, it could specify a representation like:

```yaml
provideringConfiguration:
    memory: 4
    cpu: 2
```
