### ISSUE TITLE
Framework `v0.11.2` has no proper means of setting the edition

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#3385]
This issue tracks:

* https://github.com/vmware-tanzu/tanzu-framework/issues/1797

Some plugins work in a context-aware manner. For example, the management cluster provides a different UI when the edition is `tce` vs `tkg`.

Framework `v0.11.2` is caught between updates where edition detection is moved around. When build framework, the `BUILD_EDITION` `LD_FLAG` no longer exists. You can see here the `BUILD_EDITION` is still looked up, but never used anywhere:

https://github.com/vmware-tanzu/tanzu-framework/blob/v0.11.2/common.mk#L31-L35

By default the `config.yaml` (client config) will always be structured as follows:

```yaml
apiVersion: config.tanzu.vmware.com/v1alpha1
clientOptions:
  cli:
    bomRepo: projects-stg.registry.vmware.com/tkg
    compatibilityFilePath: framework-zshippable/tkg-compatibility
    discoverySources:
    - local:
        name: default-local
        path: standalone
    edition: tkg
    repositories:
    - gcpPluginRepository:
        bucketName: tanzu-cli-framework
        name: core
    unstableVersionSelector: none
  features:
    cluster:
      custom-nameservers: "false"
      dual-stack-ipv4-primary: "false"
      dual-stack-ipv6-primary: "false"
    global:
      context-aware-cli-for-plugins: "true"
      package-based-lcm-beta: "false"
    management-cluster:
      aws-instance-types-exclude-arm: "true"
      custom-nameservers: "false"
      dual-stack-ipv4-primary: "false"
      dual-stack-ipv6-primary: "false"
      export-from-confirm: "true"
      import: "false"
      network-separation-beta: "false"
      standalone-cluster-mode: "false"
kind: ClientConfig
metadata:
  creationTimestamp: null
```

Normally, it'd be possible to use tanzu config set cli.edition tce to set this, note:

https://github.com/vmware-tanzu/tanzu-framework/blob/v0.11.2/Makefile#L63

But it does not work in this version. You'll get:

```
$ tanzu config set cli.edition tce
Error: unsupported config path parameter [cli] (was expecting 'features.<plugin>.<feature>' or 'env.<env_variable>')

✖  unsupported config path parameter [cli] (was expecting 'features.<plugin>.<feature>' or 'env.<env_variable>')
```

If you add `features.` it puts the setting in the `features` section, but that does not fix the UI.

The only way to make this work is to manually edit the config file, which won't work for our users.
