### ISSUE TITLE
unmanaged-clusters: Support custom user-managed package repositories during bootstrap

### ISSUE THREAD

**Issue by cmoulliard** [vmware-tanzu/community-edition#3458]
## Feature Request

That should be great when we create a new tanzu kind cluster using the command "tanzu uc create xxx" that we could pass as parameter the repository and/or version to be used

**Comment by stmcginnis** [comment]
Hey @cmoulliard - I believe [`--tkr`](https://github.com/vmware-tanzu/community-edition/blob/main/cli/cmd/plugin/unmanaged-cluster/cmd/create.go#L62) is what you're looking for. This defines the packages to be included as part of the "release" that gets deployed.

Further work does need to be done to make the creation of that `TKR` easier and to fully document its usage.

**Comment by joshrosso** [comment]
> Hey @cmoulliard - I believe [`--tkr`](https://github.com/vmware-tanzu/community-edition/blob/main/cli/cmd/plugin/unmanaged-cluster/cmd/create.go#L62) is what you're looking for. This defines the packages to be included as part of the "release" that gets deployed.
> 
> Further work does need to be done to make the creation of that `TKR` easier and to fully document its usage.

@stmcginnis, you **should** be correct. However, today the TKR does **not** specify the user-managed package repos.

Today, we load our user-managed repo from a `const`, which points to the most recent TCE `main` repo.

The code is already setup to expect loading multiple additional package repos:

https://github.com/vmware-tanzu/community-edition/blob/a8b8963c15303d4560e75cbbe268bf3693320a5d/cli/cmd/plugin/unmanaged-cluster/tanzu/tanzu.go#L166-L170

@jpmcb, here's my suggestion:

We should extend our config/API to allow `addtionalPackageRepos`:

```yaml
ClusterName: testit
KubeconfigPath: ""
ExistingClusterKubeconfig: ""
NodeImage: ""
Provider: kind
ProviderConfiguration: {}
Cni: calico
CniConfiguration: {}
PodCidr: 10.244.0.0/16
ServiceCidr: 10.96.0.0/16
TkrLocation: projects.registry.vmware.com/tce/tkr:v1.21.5
additionalPackageRepos:
    - projects.registry.vmware.com/tce/main:v0.11.0-alpha1
    - projects.registry.vmware.com/tce/special-repo:v1
PortsToForward: []
SkipPreflight: false
ControlPlaneNodeCount: "1"
WorkerNodeCount: "0"
```

The logic should be:

* When `additionalPackageRepos:` has `len` > 0:
    * we load **only** the package repos specified here
* When `additionalPackageRepos:` has `len` < 1:
    * we load the **default** TCE package repo (currently held in the `const`)
    
Let me know your thoughts. Thanks!
