### ISSUE TITLE
`unmanaged-cluster` kind provider should consider not using `kind-` prefix for name and context

### ISSUE THREAD

**Issue by jpmcb** [vmware-tanzu/community-edition#3470]
## Feature Request

As a followup to https://github.com/vmware-tanzu/community-edition/issues/3382, we should _consider_ renaming clusters created via the `kind` provider to _not_ have the `kind-` prefix.

For example, currently, when creating a `unmanaged-cluster`:
```
❯ tanzu unmanaged-cluster create my-cluster
```
the name and context are named as `kind-my-cluster` and `kind-my-cluster`:
```
❯ k config view --minify
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:41221
  name: kind-my-cluster
contexts:
- context:
    cluster: kind-my-cluster
    user: kind-my-cluster
  name: kind-my-cluster
current-context: kind-my-cluster
```

In order to change this behavior, it would involve mutating the kubeconfig to correctly rename the cluster and it's context. This _might_ not be as simple as 
```
%s/kind-my-cluster/my-cluster/g
```
since it's possible there are other clusters named `my-cluster`.

From a conversation in `sig-kind` (https://github.com/kubernetes-sigs/kind/issues/2668) the standard is usually to name clusters / contexts with the name of the provider first. So for kind it's `kind-`. For gke, it's `gke-`. Etc.

One thing we may want to consider is prefixing with a different discoverable name like `unmanaged-` or `tanzu-unmanaged-`.

## Describe alternatives you've considered

We could also document this well enough so it's discoverable by users. Having the `kind-` prefix lets the user know which provider had bootstrapped their cluster and enables users to have clusters of varying providers with the same "name".
