### ISSUE TITLE
Harbor fails to install when setting tlsCertificateSecretName

### ISSUE THREAD

**Issue by ciberkleid** [vmware-tanzu/community-edition#3591]
## Bug Report

The secretName for the `ca-download` volume in the harbor-core Deployment is hard-coded to `harbor-tls`.

If `tlsCertificateSecretName` in the harbor values.yaml file is set to any value other than `harbor-tls`, then the secret can't be found, the `ca-download` volume is not satisfied, and the harbor-core Pods fail to start.

The simplest fallback may be to set the secret as optional in the harbor-core overlay, but this will cause a silent failure when:
- self-signed certificates are being used, and
- tlsCertificateSecretName is not set to `harbor-tls`
In these cases, the volume would be empty, causing the CAs to not include the self-signed certificate.

Additionally, in my case, I was using a delegated certificate for contour, outside the harbor namespace (e.g. `tlsCertificateSecretName: developer-certificates/wildcard`). The solution to this problem needs to account for this use case and ensure that the secret name would pass Deployment API validation and potentially be separately configurable.

Finally, there should be a way to omit the `ca-download` volume & mount when using production TLS certificates (e.g. lets-encrypt). Including the production certificate in the CA bundle is cryptographically invalid (and dangerous). It would probably be better to disable this behavior by default, but existing users using self-signed certificates would have to enable the option, so it is a breaking change.

cc @stealthybox @vrabbi 

## Environment Details

* Build version (`tanzu version`):  Harbor package 2.3.3

## Additional Notes

I would be happy to be involved in fixing this once a decision is reached about the best approach :)

**Comment by ciberkleid** [comment]
For anyone else setting a non-default `tlsCertificateSecretName` (delegated or not), this workaround works:

```
cat <<EOF | kubectl apply -f -
---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-tls
  namespace: harbor
EOF
```

Then use `tanzu package install harbor` as usual to install the package.

**Comment by ciberkleid** [comment]
For those who prefer a quick fix that removes the `ca-download` volume and mount altogether, you can use the following workaround.

> Note:
> - This installs the Harbor package declaratively so you don't need to use `tanzu package install harbor`. 
> - Notice the PackageInstall has an annotation that references an overlay Secret below, which contains a ytt overlay to remove the volume and mount
> - The values Secret contains the modified harbor config values. Make sure to update them to your hostname, TLS secret name, and other passwords.
> - If you use a different package-management namespace, update `namespace: default` in all resources below
> - You can use `tanzu package installed delete harbor --yes` to remove the package. You will get an error saying it failed to delete a clusterrole, but you can safely ignore this error for the purposes of this workaround.

```yaml
cat <<EOF | kubectl apply -f -
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: harbor-default-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: harbor-default-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: harbor-default-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: harbor-default-sa
    ext.packaging.carvel.dev/ytt-paths-from-secret-name.0: harbor-patch-overlay
  name: harbor
  namespace: default
spec:
  packageRef:
    refName: harbor.community.tanzu.vmware.com
    versionSelection:
      constraints: 2.3.3
  serviceAccountName: harbor-default-sa
  values:
    - secretRef:
        name: harbor-default-values
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: harbor-default-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: harbor-default-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: harbor-default-sa
    namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-default-values
  namespace: default
stringData:
  harbor-default-values.yaml: |
    hostname: harbor.example.com
    tlsCertificateSecretName: developer-certificates/wildcard
    harborAdminPassword: ABCDEFG890123456
    secretKey: ABCDEFG890123456
    database:
      password: ABCDEFG890123456
    core:
      secret: ABCDEFG890123456
      xsrfKey: ABCDEFG890ABCDEFG890ABCDEFG89012
    jobservice:
      secret: ABCDEFG890123456
    registry:
      secret: ABCDEFG890123456
---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-patch-overlay
  namespace: default
stringData:
  harbor-patch-overlay.yaml: |
    #@ load("/kinds.lib.yaml", "kind_overlays")
    #@ load("@ytt:overlay", "overlay")
    
    #@ kind = kind_overlays
    #@ core_metadata = overlay.subset({"metadata": {"name": "harbor-core"}})
    
    #@overlay/match by=overlay.and_op(kind.deployment, core_metadata)
    ---
    spec:
      template:
        spec:
          containers:
            #@overlay/match by="name"
            - name: core
              volumeMounts:
                #@overlay/match by="name"
                #@overlay/remove
                - name: ca-download
          volumes:
            #@overlay/match by="name"
            #@overlay/remove
            - name: ca-download
EOF
```

Credits: paired with @stealthybox  :)
