### ISSUE TITLE
Proposal to add package for kpack dependencies

### ISSUE THREAD

**Issue by tomkennedy513** [vmware-tanzu/community-edition#3668]
## Feature Request

Currently, the kpack package in TCE requires a lot of manual steps to help bootstrap its installation with dependencies. This results in a poor install experience for users. We would like to create a new package that will provide those dependencies for users. The dependencies package would be updated at some cadence by a pipeline, pulling in the latest paketo stacks and buildpacks. Users would just need to provide an repository location and secret for the resources to be created.

## Describe alternatives you've considered

Otehr alternatives we have considered involve creating a "descriptor file" that would be used by the [kpack cli](https://github.com/vmware-tanzu/kpack-cli/blob/main/docs/kp_import.md) to import dependencies. This would require manual user intervention as well as a way for us to distribute the files to users.

## Additional context

This will be used by the App Toolkit package to provide a better experience for install

**Comment by tomkennedy513** [comment]
cc: @tylerphelan @matthewmcnew @pviraj59 @kartiklunkad26

**Comment by joshrosso** [comment]
@tomkennedy513 overall this is _likely_ ok.

Question: Would it be a bad practice to include these dependencies in the `kpack` package itself?

@seemiller

**Comment by kartiklunkad26** [comment]
I think the purpose of keeping it separate is that it enables the dependencies to iterate on a faster cadence. Dependencies can change more often (buildpacks) than kpack.

I am seeing a more general trend of “smaller” packages, that makes me believe we will see a trend of more grouped packages.

**Comment by tylerphelan** [comment]
Expected CRs in kpack-dependencies package:
```
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: base
spec:
  id: io.buildpacks.stacks.bionic
  buildImage:
    image: paketobuildpacks/build@some-sha
  runImage:
    image: paketobuildpacks/run@some-sha
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: default
spec:
  id: io.buildpacks.stacks.bionic
  buildImage:
    image: paketobuildpacks/build@some-sha
  runImage:
    image: paketobuildpacks/run@some-sha
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: default
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/java@some-sha
  - image: gcr.io/paketo-buildpacks/java-native-image@some-sha
  - image: gcr.io/paketo-buildpacks/nodejs@some-sha
  - image: gcr.io/paketo-buildpacks/go@some-sha
  - image: gcr.io/paketo-buildpacks/python@some-sha
  - image: gcr.io/paketo-buildpacks/dotnet-core@some-sha
  - image: gcr.io/paketo-buildpacks/nginx@some-sha
---
apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: base
spec:
  serviceAccountRef:
    name: kp-default-repository-serviceaccount # name is assumed from kpack-package
    namespace: kpack
  tag: #@ "{}:clusterbuilder-{}".format(data.values.repository, "base") # user input
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
    - group:
        - id: paketo-buildpacks/dotnet-core
    - group:
        - id: paketo-buildpacks/nodejs
    - group:
        - id: paketo-buildpacks/go
    - group:
        - id: paketo-buildpacks/python
    - group:
        - id: paketo-buildpacks/nginx
    - group:
        - id: paketo-buildpacks/java-native-image
    - group:
        - id: paketo-buildpacks/java
---
apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: default
spec:
  serviceAccountRef:
    name: kp-default-repository-serviceaccount
    namespace: kpack
  tag: #@ "{}:clusterbuilder-{}".format(data.values.repository, "default") # user input
  stack:
    name: base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
    - group:
        - id: paketo-buildpacks/dotnet-core
    - group:
        - id: paketo-buildpacks/nodejs
    - group:
        - id: paketo-buildpacks/go
    - group:
        - id: paketo-buildpacks/python
    - group:
        - id: paketo-buildpacks/nginx
    - group:
        - id: paketo-buildpacks/java-native-image
    - group:
        - id: paketo-buildpacks/java
```
