### ISSUE TITLE
package public names should be fully qualified

### ISSUE THREAD

**Issue by cppforlife** [vmware-tanzu/community-edition#372]
## Feature Request

currently packages have non-qualified public names: `cert-manager`. instead public names should be following CRD-like naming conventions == fully qualified names. 

Current:

```yaml
apiVersion: package.carvel.dev/v1alpha1
kind: Package
metadata:
  name: fluent-bit.1.7.2-vmware0
spec:
  publicName: fluent-bit
  version: "1.7.2-vmware0"
  # ...
```

Ideal:

```yaml
apiVersion: package.carvel.dev/v1alpha1
kind: Package
metadata:
  name: fluent-bit.tce.vmware.com.1.7.2-vmware0
spec:
  publicName: fluent-bit.tce.vmware.com
  version: "1.7.2-vmware0"
  # ...
```
