### ISSUE TITLE
packages should use kbld to use relocated image refs

### ISSUE THREAD

**Issue by cppforlife** [vmware-tanzu/community-edition#373]
## Feature Request

Assuming that each package bundle includes a list of referenced container images in .imgpkg/images.yml, each Package CR should use kbld to reference that images.yml to pick up these references. Example of kbld configuration is here: https://carvel.dev/kapp-controller/docs/latest/package-authoring/#creating-the-package-cr

```yaml
      - kbld:
          paths:
          - "-"
          - .imgpkg/images.yml
```

This ultimately supports the workflow of package copy to a different registry.
