### ISSUE TITLE
Optimize how the namespace is replaced in overlays

### ISSUE THREAD

**Issue by seemiller** [vmware-tanzu/community-edition#374]
## Feature Request

Optimize how the namespace is replaced in overlays. 

## Describe alternatives you've considered

< if applicable, what other alternatives are there and why did you not choose them? >

## Additional context

The bug in #370 was caused because a kind of resource was missed in the overlay (a ConfigMap).
```yaml
#@ ds=overlay.subset({"kind": "DaemonSet"})
#@ deployment=overlay.subset({"kind": "Deployment"})
#@ role=overlay.subset({"kind": "Role"})
#@ rb=overlay.subset({"kind":"RoleBinding"})
#@ svc=overlay.subset({"kind":"Service"})
#@ sa=overlay.subset({"kind":"ServiceAccount"})
#@overlay/match by=overlay.or_op(ds, deployment, role, rb, svc, sa), expects=2
---
metadata:
  #@overlay/match missing_ok=True
  namespace: #@ data.values.namespace
```

The overlay can be modified to search/replace all instances of a namespace without having to worry about kind.
```yaml
#@overlay/match by=overlay.subset({"metadata":{"namespace": "fluent-bit"}}), expects=3
---
metadata:
  namespace: #@ data.values.namespace
```
