### ISSUE TITLE
Etcd 3.5.x should not be used or corrupt check should be in place

### ISSUE THREAD

**Issue by stmcginnis** [vmware-tanzu/community-edition#3840]
## Bug Report

TCE v0.11.0 shipped using etcd 3.5.0. Just prior to release, a notice was sent out by the etcd maintainers that there is a data consistency issue in the 3.5.x releases and that it should not be used. The problem affects versions v3.5.0, v3.5.1, v3.5.2

https://groups.google.com/g/etcd-dev/c/sad9tgmKU7Y/m/vhArFVevBgAJ

See https://github.com/etcd-io/etcd/issues/13766 for more details.

## Expected Behavior

TCE should ship with a version of etcd that does not have known data consistency issues.

**Comment by joshrosso** [comment]
or if clusters continue to ship with 3.5.x in the near term, we should:

* Enable data corruption check with `--experimental-initial-corrupt-check` flag. The flag is the only reliable automated way of detecting an inconsistency. This mode has seen significant usage in production and is going to be promoted as default in etcd v3.6.

**Comment by joshrosso** [comment]
Validated in our TKr BOM, we now have this in place:

```
kubeadmConfigSpec:
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  imageRepository: projects.registry.vmware.com/tkg
  kubernetesVersion: v1.22.8+vmware.1
  etcd:
    local:
      dataDir: /var/lib/etcd
      imageRepository: projects.registry.vmware.com/tkg
      imageTag: v3.5.2_vmware.3
      extraArgs:
        experimental-initial-corrupt-check: true
```
