### ISSUE TITLE
Provide a new parameter to configure altNames - certificate to access the HTTPS harbor registry externally

### ISSUE THREAD

**Issue by cmoulliard** [vmware-tanzu/community-edition#3917]
## Feature Request

Provide a new parameter part of the `values.yaml` file in order to configure the `altNames` section of the Harbor Selfsigned CA certificate to allow to access the Harbor registry externally using the FQName such as `harbor.$VM_IP.nip.io`.

This parameter should be able to add the following new names - https://github.com/halkyonio/tce/blob/aaf744777ce3951dbc9651d38e214e330a22af4a/scripts/install_harbor.sh#L64-L66

Ideally we should also have a boolean parameter (e.g. updateContainerd) to tell to perform the following actions:
- Update the containerd config TOML file to add a mirror and config, 
- Copy the certificate/key generated to the path where the containerd can load them
- Restart the containerd service
- Create the harbor-tls secret - see: https://github.com/halkyonio/tce/blob/main/scripts/install_harbor.sh#L154-L157
**Question**: Can we do that as part of a package installation ?

See this project as example: https://github.com/halkyonio/tce/blob/main/scripts/install_harbor.sh#L94-L115.

**Comment by jpmcb** [comment]
Hi @cmoulliard - thanks for surfacing this. cc @vmware-tanzu/pkg-harbor-owners

**Comment by cmoulliard** [comment]
A new function should then be created (and the existing one revisited):

```
#@ def generate_dns_names(name, ip_domain_name):
#@   return [name + "."+ ip_domain_name]
#@ end

#@ def generate_kubernetes_dns_names(name, namespace):
#@   full_name = name + "." + namespace
#@   svc_name = full_name + ".svc"
#@   svc_cluster_local_name = svc_name + ".cluster.local"
#@   return [name, full_name, svc_name, svc_cluster_local_name]
#@ end
```
and a new value passed 

```
#@ harbor_ip_domain_name = values.ip_domain_name
--- #@ generate_certificate(...[generate_dns_names("harbor",harbor_ip_domain_name),generate_dns_names("notary",harbor_ip_domain_name)],...)
```

to generate such a Certificate YAML
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dummy-core-internal-cert
  namespace: dummy
spec:
  secretName: dummy-core-internal-tls
  duration: 87600h
  renewBefore: 360h
  organization:
  - Project Dummy
  commonName: dummy-core
  isCA: false
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
  - server auth
  - client auth
  dnsNames:
  - - harbor.1.1.1.1.nip.io
  - - notary.1.1.1.1.nip.io
  ipAddresses: []
  issuerRef:
    name: dummy-ca-issuer
    kind: Issuer
    group: cert-manager.io
```
