### ISSUE TITLE
Add schemas with backward compatibilities to calico packages

### ISSUE THREAD

**Issue by 12345lcr** [vmware-tanzu/community-edition#4051]
## Bug Report

TCE calico packages are introducing input schemas to restrict the input values format for the packages, but we need to consider the backward compatibilities for upgrading.

Below is the example of the deprecated image fields that are useless for now but may exists in the clusters' data values secrets, who was upgraded from older releases.
```
calico:
  image:
    repository: #@ get_image_repo_for_component(calicoImages.calicoCniImage)
    pullPolicy: IfNotPresent
  cniImage:
    path: #@ calicoImages.calicoCniImage.imagePath
    tag: #@ calicoImages.calicoCniImage.tag
  nodeImage:
    path: #@ calicoImages.calicoNodeImage.imagePath
    tag: #@ calicoImages.calicoNodeImage.tag
  podDaemonImage:
    path: #@ calicoImages.calicoPodDaemonImage.imagePath
    tag: #@ calicoImages.calicoPodDaemonImage.tag
  kubeControllerImage:
    path: #@ calicoImages.calicoKubecontrollerImage.imagePath
    tag: #@ calicoImages.calicoKubecontrollerImage.tag
```

## Expected Behavior

Add these deprecated image fields to the schemas for backwards compatibility.

## Steps to Reproduce the Bug

1. Update the values.yaml to include these image fields in the current calico 3.19.1 package
2. Use ytt to generate the final pattern of the calico manifests
3. The ytt will print out the failure that says these image fields are not allowed by schemas.
