### ISSUE TITLE
Package Repository should be an imgpkg bundle

### ISSUE THREAD

**Issue by seemiller** [vmware-tanzu/community-edition#435]
## Feature Request

Imgpkg v0.6.0 now supports [nested bundles](https://github.com/vmware-tanzu/carvel-imgpkg/releases/tag/v0.6.0). The recommendation is to update to this version of imgpkg and convert our package repository to use this new feature. 

This means changing our PackageRepository CRs to fetch `imgpkgBundle` instead of `image`

Current:
```yaml
spec:
  fetch:
    image:
      url: projects.registry.vmware.com/tce/foo@sha256:abc123...
```

Desired:
```yaml
spec:
  fetch:
    imgpkgBundle:
      image: projects.registry.vmware.com/tce/foo@sha256:abc123...
```

This change will require a modification to the Tanzu CLI package plugin to support `fetch.imgpkgBundle`

## Describe alternatives you've considered

We could just continue using images, but we will miss out on the capabilities that Carvel is building around imgpkgBundles

## Additional context

-
