### ISSUE TITLE
Docker Desktop GH action to publish images to DH

### ISSUE THREAD

**Issue by jorgemoralespou** [vmware-tanzu/community-edition#4387]
## Bug Report
As the extension repo has been moved to TCE we need to publish the generated extension to Docker Hub (https://hub.docker.com/repository/docker/vmware/vmware-tanzu-community-edition-extension-for-docker-desktop). 

Previous GH action will not work.
https://github.com/vmware-tanzu/community-edition/blob/main/extensions/docker-desktop/.github/workflows/build-image.yaml

**Comment by jpmcb** [comment]
I think we'll need to not couple the extension to official TCE tags and releases. So instead of having something that triggers off of a push to the main branch with a tag:
```
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
```

we could just make it a manual trigger via a `workflow_dispatch`:
```
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version tag for Docker Desktop extension image to be pushed to docker hub"
        required: true
```

which can be triggered manually via the github command line tool. Something like:
```
gh workflow run --repo https://github.com/vmware-tanzu/community-edition/ \
  --ref main \
  release-tag-docker-dekstop-extension.yaml \
  --raw-field release_version=v1.2.3
```

This would be an ok intermittent solution until we figure out what we want to do about releasing this automatically.
