### ISSUE TITLE
Harbor tlsCertificate check incomplete

### ISSUE THREAD

**Issue by MinerYang** [vmware-tanzu/community-edition#4941]
## Bug Report

when I filled up only `ca.crt`, no errors pop up and package shows reconcile succeeded.  But these tlsCertificate invalid actually
```
tlsCertificate:
  tls.crt:
  tls.key:
  ca.crt:
```

## Expected Behavior
When user using self tlsCertificate,  only filled up the ca.crt and leave the rest two blank, harbor package should errors out in case of user misunderstood it is valid.
