### ISSUE TITLE
Allow configuration for external-dns to publish metrics

### ISSUE THREAD

**Issue by doddatpivotal** [vmware-tanzu/community-edition#5277]
## Feature Request

External-dns can expose metrics.  However, in order to configure it to do so, you must set a deployment arg specifying the metrics address, and then add labels to the deployment pods to set appropriate prometheus metrics.  The current implementation of the values schema provides ability to set the deployment args, but you can not set the deployment pod labels.

```yaml
deployment:
  args:
    - --metrics-address=:7979 #! ensures external dns exposes metrics
```

## Describe alternatives you've considered

I have created an overlay to apply the deployment pod labels, but would like to be able to configure observability directly using the values file.

```yaml
#@ load("@ytt:overlay", "overlay")
#@overlay/match by=overlay.subset({"metadata":{"name":"external-dns"}, "kind": "Deployment"})
---
spec:
  template:
    #@overlay/match missing_ok=True
    metadata:
      #@overlay/match missing_ok=True
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "7979"
```
