### ISSUE TITLE
Missing must-have labels in configmap restic-restore-action-config when enabling restic

### ISSUE THREAD

**Issue by jhuisss** [vmware-tanzu/community-edition#5575]
https://github.com/vmware-tanzu/community-edition/blob/096a8bad98e1542c21ba7afd6d56b1a286b1411a/addons/packages/velero/1.9.2/bundle/config/overlays/velero/overlay-restic.yaml#L54

According to https://velero.io/docs/v1.9/restic/#customize-restore-helper-container, velero uses the labels to identify this comfigmap rather than the name, so the labels should be used in the ConfigMap.
```
  labels:
    # this value-less label identifies the ConfigMap as
    # config for a plugin (i.e. the built-in restic restore
    # item action plugin)
    velero.io/plugin-config: ""
    # this label identifies the name and kind of plugin
    # that this ConfigMap is for.
    velero.io/restic: RestoreItemAction
```
