### ISSUE TITLE
Tanzu Packaging Process doc gives incorrect advice.

### ISSUE THREAD

**Issue by GrahamDumpleton** [vmware-tanzu/community-edition#813]
## Feedback

In the doc:

* https://github.com/vmware-tanzu/tce/blob/main/docs/designs/tanzu-packaging-process.md

There is an example for ``vendir`` config of:

```
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: config
  contents:
  - path: upstream
    git:
      url: https://github.com/open-policy-agent/gatekeeper
      ref: origin/master
    newRootPath: deploy
```

In my understanding of how ``vendir`` works, I believe this is an incorrect config in the context of the directory structure being used.

The problem is that with this config it is the ``config`` directory which ends up being managed by ``vendir`` and not ``config/upstream`` as described. The result is that when ``vendir sync`` is run, everything under ``config`` is deleted and replace and not just what is under ``config/upstream``. As a result the ``config/overlay`` directory added by the user gets deleted.

## Suggested Changes

Believe the config should be:

```
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: config/upstream
  contents:
  - path: .
    git:
      url: https://github.com/open-policy-agent/gatekeeper
      ref: origin/master
    newRootPath: deploy
```

## Environment Details

N/A

cc @jorgemoralespou
