### ISSUE TITLE
repo channel template is missing yaml

### ISSUE THREAD

**Issue by seemiller** [vmware-tanzu/community-edition#819]
## Bug Report

The `create-channel.sh` script is missing this yaml:

```yaml
  packageSpec:
    syncPeriod: 5m
    deploy:
      kappWaitTimeout: 5m
```

This will cause problems with when trying to generate the package manifest.

## Environment Details

* Build version (`tanzu version`):  
* Operating System (client):
